# Generated by Django 4.2.11 on 2025-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
